FROM node:18 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build -- --configuration=production

FROM nginx:1.25.4-alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist/health-app /usr/share/nginx/html

EXPOSE 80
